In [2]:
import pandas as pd
import os

In [7]:
pwd

'C:\\Users\\Ravina'

In [8]:
os.chdir("D:\DATA_SCIENCE_INTERNSHIP\SWYNEX_Data_Preparation")

In [9]:
pwd

'D:\\DATA_SCIENCE_INTERNSHIP\\SWYNEX_Data_Preparation'

In [10]:
df=pd.read_csv("Housing_data.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [11]:
df.columns=df.columns.str.title()
df

,Price,Area,Bedrooms,Bathrooms,Stories,Mainroad,Guestroom,Basement,Hotwaterheating,Airconditioning,Parking,Prefarea,Furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Price             545 non-null    int64
 1   Area              545 non-null    int64
 2   Bedrooms          545 non-null    int64
 3   Bathrooms         545 non-null    int64
 4   Stories           545 non-null    int64
 5   Mainroad          545 non-null    str
 6   Guestroom         545 non-null    str
 7   Basement          545 non-null    str
 8   Hotwaterheating   545 non-null    str
 9   Airconditioning   545 non-null    str
 10  Parking           545 non-null    int64
 11  Prefarea          545 non-null    str
 12  Furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 69.2 KB

In [13]:
df.describe()

,Price,Area,Bedrooms,Bathrooms,Stories,Parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [15]:
df.isnull().sum()

Price               0
Area                0
Bedrooms            0
Bathrooms           0
Stories             0
Mainroad            0
Guestroom           0
Basement            0
Hotwaterheating     0
Airconditioning     0
Parking             0
Prefarea            0
Furnishingstatus    0
dtype: int64

In [18]:
df.dtypes

Price               int64
Area                int64
Bedrooms            int64
Bathrooms           int64
Stories             int64
Mainroad              str
Guestroom             str
Basement              str
Hotwaterheating       str
Airconditioning       str
Parking             int64
Prefarea              str
Furnishingstatus      str
dtype: object

In [20]:
df.duplicated().sum()

np.int64(0)

In [25]:
categorical_columns=['Mainroad','Guestroom','Basement','Hotwaterheating','Airconditioning','Prefarea','Furnishingstatus']
df[categorical_columns]=df[categorical_columns].astype('category')

In [26]:
df.dtypes

Price                  int64
Area                   int64
Bedrooms               int64
Bathrooms              int64
Stories                int64
Mainroad            category
Guestroom           category
Basement            category
Hotwaterheating     category
Airconditioning     category
Parking                int64
Prefarea            category
Furnishingstatus    category
dtype: object

In [30]:
for col in categorical_columns:
    print(col,":",df[col].unique())

Mainroad : ['yes', 'no']
Categories (2, str): ['no', 'yes']
Guestroom : ['no', 'yes']
Categories (2, str): ['no', 'yes']
Basement : ['no', 'yes']
Categories (2, str): ['no', 'yes']
Hotwaterheating : ['no', 'yes']
Categories (2, str): ['no', 'yes']
Airconditioning : ['yes', 'no']
Categories (2, str): ['no', 'yes']
Prefarea : ['yes', 'no']
Categories (2, str): ['no', 'yes']
Furnishingstatus : ['furnished', 'semi-furnished', 'unfurnished']
Categories (3, str): ['furnished', 'semi-furnished', 'unfurnished']

In [33]:
for col in categorical_columns:
    df[col] = df[col].astype(str).str.capitalize()
    df[col] = df[col].astype('category')

In [37]:
df.to_csv('cleaned_housing_data.csv', index=False)